workflows:
  ios-build:
    name: iOS Build Workflow
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean and Install Pods
        script: |
          cd ios
          rm -rf Podfile.lock Pods
          pod repo update
          pod install
          cd ..
      - name: Build iOS App
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa
